In [3]:
import numpy as np
from sklearn.neural_network import MLPClassifier

# imagenes a clasificar
[
    [1,0],
    [0,0] = 1
]

[
    [0,0],
    [0,1] = 2
]

[
    [1,1],
    [0,0] = 3
]

[
    [1,0],
    [1,1] = 4
]

In [19]:
uno = np.array([
    [1,0],
    [0,0]
])

dos = np.array([
    [1,0],
    [0,1]
])

tres = np.array([
    [1,1],
    [0,0]
])

cuatro = np.array([
    [1,0],
    [1,1]
])

In [5]:
uno

array([[1, 0],
       [0, 0]])

In [6]:
uno.shape

(2, 2)

In [ ]:
uno[0,0] # uno[0][0]

np.int64(1)

In [12]:
uno.reshape(1,4).shape

(1, 4)

In [13]:
uno.flatten().shape

(4,)

In [20]:
uno = uno.flatten()
dos = dos.flatten()
tres = tres.flatten()
cuatro = cuatro.flatten()

In [21]:
dataset = [uno,dos,tres,cuatro]

In [22]:
dataset

[array([1, 0, 0, 0]),
 array([1, 0, 0, 1]),
 array([1, 1, 0, 0]),
 array([1, 0, 1, 1])]

In [24]:
X = dataset

In [25]:
Y = np.array([[1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]])

In [26]:
Y

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])